### ISSUE TITLE
References of Mumbai causes Widgets to stop working

### ISSUE THREAD

**Issue by srph** [hyperlane-xyz/hyperlane-widgets#7] opened 2024-05-02 06:29 UTC
I recently clean-installed our hyperlane-warp-template fork (this meant removing caches and package-lock), and I found that `@hyperlane-xyz/widgets`, specifically `ChainLogo` crashes because it has references to Mumbai which seems to have been removed in https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3521/files. I'm not sure how the sdk generates the `Chains` constant (I couldn't find it)

[On this line](https://github.com/hyperlane-xyz/hyperlane-widgets/blob/ddb4d8cd6c3906d33ef3a6e5279a11eef8925a81/src/icons/ChainLogo.tsx#L70), this project references `Chains.mumbai` which I can't find when inspecting my `node_modules` folder.

This is what my package.json looks like:

```
"@hyperlane-xyz/sdk": "^3.8.1",
"@hyperlane-xyz/utils": "^3.8.1",
"@hyperlane-xyz/widgets": "^3.8.0",
```

From my understanding, `^` installs any _minor_ patches. This means, I'm installing sdk and utils `3.10.0` which have _breaking_ changes for this project.

**Comment by jmrossy** [comment] 2024-05-16 16:56
Hi @srph, sorry I didn't see this sooner.

You're entirely correct! The missing chain was indeed the cause of your error and the recent changes haven't properly observed semantic versioning, sorry. 

We're overhauling the way the SDK, CLI, and Widget libs work right now. Instead of having metadata and logos for specific chains baked in, the utilities will take an `IRegistry` param which they'll use to fetch that kind of data. See [here](https://docs.hyperlane.xyz/docs/reference/registries) and [here](https://github.com/hyperlane-xyz/hyperlane-registry).

Thanks for your patience as we make the transition. As for this specific bug, it should be fixed by #8

**Closed as completed by jmrossy** 2024-05-16 16:56 UTC
